# Add bassam quotes here
bnaji_quotes=(
    "When 911 have an emergency they call Bassam." 
    "Bassam is the reason why Waldo is hiding." 
    "Bassam can speak Braille."
    "Bassam can divide by zero."
    "Bassam can delete the Recycling Bin."
    "Bassam can slam a revolving door."
    "Bassam can drown a fish."
    "Bassam can hear sign language."
    "Bassam can judge a book by its cover."
    "Bassam can kill two Dwayne The Rock Jonhson with one bird."
    "Bassam can lick his elbow."
    "Bassam can make onions cry."
    "Bassam can play the violin with a piano."
    "Bassam can set ants on fire with a magnifying glass. At night."
    "Bassam can speak French... In Russian."
    "Bassam can strangle you with a cordless phone."
    "Bassam can tie his shoes with his feet."
    "Bassam can win a game of Connect Four in only three moves."
    "Bassam can write a book in a day."
    "Bassam wrote the dictionary to allow you to understand him."
    "Bassam can write a full thesis on a single grain of rice."
    "Bassam can write a novel with his eyes closed."
    "Bassam can write a novel with his toes."
    "Bassam's email is gmail.@bassam.com ."
    "If you work hard enough, one day you will be as good as bassam"
    "Bassam played in every Star Wars movie, he was the force"
    "When you ask Bassam what time it is, he says, 'Two seconds till.' After you ask, 'Two seconds to what?' he roundhouse kicks you in the face."
    "Bassam can build a snowman out of rain."
    "Bassam doesn't cheat death, he wins fair and square."
    "Bassam doesn't do push ups, he pushes the world down. Scientists now study this pehonomenon and called it earth quakes."
    "Bassam doesn't wear a watch, he decides what time it is."
    "Bassam farted once, there was no big bang, that's how the universe was created."
    "Bassam has already been to Mars; that's why there are no signs of life."
    "Ok enough ... Bassam has a diary, it is called the Guinness Book Of World Records."
    "Bassam has a grizzly bear carpet in his room. The bear isn't dead it is just afraid to move."
    "Bassam has a mug of nails instead of coffee in the morning."
    "Bassam has a pet named after him. It is called the Bassamosaurus."
    "John Wick called Bassam to tell him he would find him and apologize for killing his dog."
    "Cupid shot bassam and fell in love"
    "Bassam can make a fire by rubbing two ice cubes together."
    "Bassam hits 1,000,000 subscribers on YouTube with no videos."
    "Bassam hit a home run in a football game."
    "Bassam hit 11 out of 10 targets with 9 bullets"
    "Bassam had a staring contest with the sun and won."
    "Bassam had a bet with batman, the loser would be on nightshift."
    "Bassam simply walked into Mordor."
    "Bassam finished Transcendence by the time you finished reading this."
    "Bassam said 'I'll be back' and he did."
    "Bassam once had a heart attack, his heart lost."
    "Bassam's tears can cure cancer, too bad he never cries."
    "Bassam's calendar goes straight from March 31st to April 2nd; no one fools Bassam."
    "Bassam's computer has no backspace button, Bassam doesn't make mistakes."
    "The only time Bassam was wrong was when he thought he had made a mistake."
    "Bassam once kicked a horse in the chin. Its descendants are known today as Giraffes."
    "Bassam kicked the world once and it never stopped spinning."
    "A Dinasaur looked at Bassam the wrong way once. You know what happened to them..."
    "Bassimology is the study of Bassam."
    "Bassboungology is the study of Bassam's bounces."
    "'Bassam' is Arabic for 'The Boss'."
    "Basbousa is Arabic for 'Bassam's Cousin'."
    "Life is not about how many breaths you take, it's about how many times Bassam takes your breath away."
    "Tough times never last, but tough people do. Bassam is the toughest."
    "42 is the meaning of life, the universe and everything. Bassam is the meaning of 42."
    "Bassam is the only person who can punch a cyclops between the eye."
    "Running away from Bassam is considered an extreme sport."
    "Ghosts sit around the campfire and tell Bassam stories."
    "Fear of spiders is arachnophobia, fear of tight spaces is claustrophobia, fear of Bassam is called Logic."
    "Funny how Bassam can be in a room with 100 people, but he can still make you feel like the only one."
    "You don't have to be faster than the bear to get away. You just have to be faster than the slowest guy running from Bassam."
    "Foul language was invented by Bassam. He calls it 'Talking'."
    "He who laughs last, laughs best. He who laughs at Bassam, it's definitely his last."
    "People with amnesia still remember Bassam."
    "Quantum Theory states that Bassam can be in two places at the same time."
    "Quality is better than quantity, unless you are talking about Bassam."
    "We all know the speed of light, but what is the speed of dark? Bassam knows."
    "Every time Bassam goes for a swim, dolphins appear."
    "Roses are red, violets are blue, Bassam is awesome, and so are you."
    "The only thing that can cut diamonds is Bassam."
    "You can't spell Bassam without 'Bassam'."
    "Unicorns used to exist. Bassam killed the last one."
    "If you spell Bassam in Scrabble, you win. Forever."
    "Once a cobra bit Bassam's leg. After five days of excruciating pain, the cobra died."
    "People say that Bassam is a myth. Those 'people' are now dead."
    "{Bassam} is the only word in the dictionary that is spelled correctly."
    "A picture is worth a thousand words. A Bassam is worth a billion words."
    "A Bassam a day keeps the doctor away."
    "Some people wear Superman pajamas. Superman wears Bassam pajamas."
    "Death once had a near-Bassam experience."
    "He who lives by the sword, dies by the sword. He who lives by Bassam, dies by the roundhouse kick."
    "Keep calm and Bassam on."
    "Love means never having to say Bassam."
    "Zombies look both ways before crossing Bassam."
    "X-rays were invented by Bassam to scan for broken bones."
    "Chuck Norris once met Bassam. The result? Bassam Roundhouse kicked Chuck Norris into the sun."
    "Vampires are allergic to Bassam."
    "Never look a gift Bassam in the mouth."
    "Never judge a book by its cover. Never judge Bassam by his roundhouse kick."
    ">Bassam is the only person who can kick you in the back of the face."
    "? Bassam."
    "? Bassam is the answer"
    "! Bassam"
    "#Bassam"
    "Sometimes Bassam goes to the zoo and lets the animals take pictures of him."
    "Perhaps Bassam is the answer to the question."
    "Of course Bassam is real. He just chooses to be invisible sometimes."
    "Two wrongs don't make a right. Bassam makes two wrongs make a right."
    "Turn the other cheek. Bassam doesn't need to."
    "You can lead a horse to water. Bassam can make him drink."
    "Reality is just a crutch for people who can't handle Bassam."
    "Only Bassam can prevent forest fires."
    "Thunder is the sound of Bassam bowling."
    "Skin cancer cures Bassam."
    "Oil and water don't mix. Bassam can."
    "Soluble means able to be dissolved. Bassam means able to dissolve."
    "Sugar and spice and everything nice. Bassam is all of these and more."
    "Sunshine is the best medicine. Bassam is the best sunshine."
    "Poof! Bassam is here."
    "Wow is Bassam spelled upside down."
    "Amazing is Bassam spelled sideways."
    "Shhh! Bassam is sleeping."
    "Silence is golden. Bassam is platinum."
    "Artificial intelligence is no match for natural stupidity. Bassam is no match for artificial intelligence."
    "Paint the town red? Bassam can paint the town invisible."
    "Art is in the eye of the beholder. Bassam is in the eye of the art."
    "Bassam is the only person who can make a triangle with four sides."
    "Bassam is the only person who can make a circle with three sides."
    "Bassam is the only person who can make a square with five sides."
    "Business is business. Bassam is Bassam."
    "Love begins with a smile, grows with a kiss, and ends with a tear. Bassam begins with a roundhouse kick, grows with a roundhouse kick, and ends with a roundhouse kick."
    "I love you. Bassam loves you more."
    "Great minds think alike. Bassam thinks for everyone."
    "Gravity doesn't exist. Bassam just roundhouse kicks you to the planet."
    "Taste is in the mouth of the beholder. Bassam is in the mouth of the taste."
    "Live and let live. Bassam lives and lets you live."
    "Legends are born, not made. Except for Bassam."
    "akjfaksldfhaksjdhfjalskdhfjsdf Bassam understands this in 39 different languages"
    "The world is your oyster. Bassam is your world."
    "Butterflies are free. Bassam is freer."
    "Hieroglyphics is the written language of Bassam."
    "Alphabet soup spells Bassam."
    "Eureka! Bassam."
    "Transcendentalism is the study of Bassam."
    "Fractions are just Bassam trying to count."
    "Fractals are just Bassam trying to draw."
    "File descriptors are just Bassam trying to open a file."
    "Assembly language is just Bassam trying to program."
    "Kernel panics are just Bassam trying to reboot."
    "Bassam writes his own compiler."
    )

RANDOM=$$$(date +%s)
echo "Remember little one ..."
wisdom=${bnaji_quotes[ $RANDOM % ${#bnaji_quotes[@]} ]}
echo $wisdom